# Paths
export PATH="$HOME/.local/dotbin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/Applications"
export PATH="$(dotuniq ':' "$PATH")"

export PYTHONPATH="$HOME/.local/dotlib/python:$PYTHONPATH"
export PYTHONPATH="$(dotuniq ':' "$PYTHONPATH")"

# ssh-agent: useful to avoid having git-lfs asking for credentials multiple times
# note: the lifetime flag (-t) is overriden by a lifetime specified trough
# ssh-add or ~/.ssh/config AddKeysToAgent.
# note: do not forget to add `AddKeysToAgent <lifetime>` in '~/.ssh/config'.
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 300 -a "$SSH_AUTH_SOCK" # note: overriden by value set
fi

# Interactive shell only
[[ $- == *i* ]] && {
    # 256 colors in virtual console
    [[ "$TERM" == "linux" ]] && export TERM='xterm-256color'

    # Disable bash history persistence (RAM history still works).
    export HISTFILE=/dev/null
    export HISTSIZE=10000

    # Pager
    export PAGER='less'
    export LESS='--RAW-CONTROL-CHARS --no-init'
    export LESSHISTFILE='-'

    # Editor
    export VISUAL='micro'
    export EDITOR='micro'

    # Check the window size after each command and, if necessary, update the
    # values of LINES and COLUMNS.
    shopt -s checkwinsize

    # Handle **
    shopt -s globstar

    # Includes
    source "$HOME/.config/bashrc.d/alias.sh"
    source "$HOME/.config/bashrc.d/complete.sh"
    source "$HOME/.config/bashrc.d/prompt.sh"
}
