# Interactive shell only
[[ $- == *i* ]] && {
    # 256 colors in virtual console
    [[ "$TERM" == "linux" ]] && export TERM='xterm-256color'

    # Disable bash history persistence (RAM history still works).
    export HISTFILE=/dev/null

    # Pager
    export PAGER='less'
    export LESS='--RAW-CONTROL-CHARS'
    export LESSHISTFILE='-'

    # Check the window size after each command and, if necessary, update the
    # values of LINES and COLUMNS.
    shopt -s checkwinsize

    # Handle **
    shopt -s globstar

    # Includes
    for file in "$HOME/.bashrc.d/"*.sh; do
        source "$file"
    done
}

{
    # Path
    export PATH="$HOME/.local/bin:$PATH"
    export PATH="$HOME/.local/dotbin:$PATH"
}
