# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Variables

## Disable bash history persistence (RAM history still works).
export HISTFILE=/dev/null

## Pager
export PAGER='less'
export LESS='--quit-if-one-screen --RAW-CONTROL-CHARS'
export LESSHISTFILE='-'

# Options

## Check the window size after each command and, if necessary, update the values
## of LINES and COLUMNS.
shopt -s checkwinsize

## Handle **
shopt -s globstar

## Completion fallback for commands handled by bash-completion _longopt and _cd.
## Restore glob completion. See unmerged pull-request [Handle ambiguous globs
## gracefully #77](https://github.com/scop/bash-completion/pull/77).
compopt -o bashdefault ls cd

# Aliases
alias ls='ls --group-directories-first --color=auto --human-readable'
alias grep='grep --color=auto'
alias cb='xclip -rmlastnl -selection clipboard'
alias ip='ip -color'

## cdc - Change directory to current one. Fix "unreachable" directory problems
## after unmounting and remounting a filesystem.
alias cdc='cd "$PWD"'

# Includes

## promptline & shell title
. ~/.prompt.sh

## fuzzy completion
. ~/.fzf.sh
bind -x '"\C-i": "_fzf_complete"'
