# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# promptline & shell title
. ~/.prompt.sh

# append to the history file, don't overwrite it
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Handle **
shopt -s globstar

# Aliases
alias ls='ls --group-directories-first --color=auto'
alias grep='grep --color=auto'
alias rm='rm --preserve-root'
alias cb='xclip -selection c'
alias ip='ip -c'
