# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Promptline & shell title
. ~/.prompt.sh

# Disable bash history persistence (RAM history still works).
export HISTFILE=/dev/null

# Pager
export PAGER='less'
export LESS='--quit-if-one-screen --RAW-CONTROL-CHARS'
export LESSHISTFILE='-'

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Handle **
shopt -s globstar

# Aliases
alias ls='ls --group-directories-first --color=auto --human-readable'
alias grep='grep --color=auto'
alias cb='xclip -rmlastnl -selection clipboard'
alias ip='ip -color'

## cdc - Change directory to current one. Fix "unreachable" directory problems
## after unmounting and remounting a filesystem.
alias cdc='cd "$PWD"'
