#!/bin/bash

for f in /etc/X11/xinit/xinitrc.d/*.sh ; do
    . "$f"
done
unset f

# https://bugs.archlinux.org/task/72661
# https://gitlab.freedesktop.org/xorg/xserver/-/issues/1241
xrandr --dpi 96

exec i3
