#!/bin/sh

user_resources="$HOME/.Xresources"
[ -f $user_resources ] && xrdb -merge $user_resources

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3
