#!/bin/bash

set -o errexit -o nounset

# Prevent committing changes containing specific keywords.
keywords() {
    local kwex='(TODO|DEBUG)'
    local diff; diff="$(git diff --color='always' --staged -G "$kwex")"
    if grep --quiet "$kwex" <<< "$diff"; then
        echo "$(tput smso)Global pre-commit hook: keywords$(tput sgr0)"
        echo "$diff"
        exit 1
    fi
}

keywords
