#!/bin/bash

set -o errexit -o nounset

# Warn on commits containing specific keywords.
keywords() {
    local diff; diff="$(git diff --color='always' --staged \
        -G '(TODO|DEBUG|FIXME)')"
    if [[ -n "$diff" ]]; then
        echo "$(tput smso)Global pre-commit hook: keywords$(tput sgr0)"
        echo "$diff"
    fi
}

keywords
